-
- name: new k8s servers
  hosts: new_rke
  remote_user: root

  tasks:
  - name: move certs
    copy:
          src: /certs
          dest: /

  - name: get docker
    apt:
      pkg:
        - docker
        - docker.io
  
  - name: install kubectl
    shell:
          apt install dockere 

  - name: move more certs
    copy:
          src: /etc/docker/certs.d
          dest: /etc/docker/
  
  - name: add kubectl
    copy:
          src: /root/kubectl_1.24.2_amd64.deb
          dest: /root/kubectl_1.24.2_amd64.deb
    
  - name: install kubectl
    shell:
          apt install /root/kubectl_1.24.2_amd64.deb
    
  - name: delete deb file
    file:
          path: /root/kubectl_1.24.2_amd64.deb
          state: absent

  - name: change data dir
    copy:
          src: /etc/docker/daemon.json
          dest: /etc/docker/

  - name: changes data dir
    shell:
      cmd: |
        rsync P /var/lib/docker/ "/data"
        cp p /var/lib/docker/* "/data/docker"
        cp p /var/lib/docker "/data/"
        mv /var/lib/docker/ /var/lib/docker.old
        service docker restart
        rm f /var/lib/docker.old/

  - name: get helm
    copy:
          src: /bin/helm
          dest: /bin/
    
  - name: add permission
    shell:
          chmod +x /bin/helm
  
  - name: restart docker
    shell:
          systemctl restart docker


